spring.application.name=FPSKGuideBot
bot.token=${ID_TOKEN:8708949062:AAECPvamPo3yGEFUiujYd0b3kpPQ706LJeQ}
bot.username=@FPSKGuide_bot

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/fpsk_dataBase
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Operator Configuration
operator.chat.id=1083645714