spring.application.name=FPSKGuideBot
bot.token=${ID_TOKEN}
bot.username=@FPSKGuide_bot

# Database Configuration
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/fpsk_dataBase}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Operator Configuration
operator.chat.id=${OPERATOR_CHAT_ID}